name: Students Table Creation

on:
  push:
    branches: ["main", "sql-hands-on"]

jobs:
  runs-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Get My Code
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install mysql-client -y

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to start..."
          until mysqladmin ping -h mysql -u root -proot --silent; do
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Run SQL File
        run: mysql -h mysql -u root -proot testdb < SQL/students.sql
