name: Students Table Creation

on:
  push:
    branches: ["main", "sql-hands-on"]

jobs:
  runs-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_pass
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install mysql-client -y

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to start..."
          retries=15
          until mysql -h mysql -u ci_user -pci_pass -e "SELECT 1;" >/dev/null 2>&1 || [ $retries -eq 0 ]; do
            echo "Waiting... ($retries)"
            retries=$((retries-1))
            sleep 2
          done

          if [ $retries -eq 0 ]; then
            echo "MySQL did not start in time"
            exit 1
          fi

          echo "MySQL is ready!"

      - name: Run SQL File
        run: mysql -h mysql -u ci_user -pci_pass testdb < SQL/students.sql
